version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
    # expose the Minecraft server port outside of container
    - 25565:25565
    mem_limit: 8G
    environment:
      # REQUIRED for all types
      EULA: "TRUE"
      # Set server type (vs the default of vanilla)
      TYPE: FORGE
      SERVER_NAME: "FoxCraft"
      DIFFICULTY: normal
      OPS: KevinLivek,BinaryVixen899
      MEMORY: "8G"
      #ICON
      VERSION: 1.16.5
      FORGEVERSION: 36.2.0
      ALLOW_NETHER: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      SPAWN_ANIMALS: "TRUE"
      SPAWN_MONSTERS: "TRUE"
      SPAWN_NPCS: "TRUE"
      MOTD: "Now with more Foxes!"
      #ENABLE_ROLLING_LOGS:
      TZ: AMERICA/LOS_ANGELES 
      LEVEL_TYPE: "BIOMESOP"
      #USE_AIKAR_FLAGS: "TRUE"
    restart: always
    volumes:
      # use a named, managed volume for data volume
      - mc_forge:/data
      # attach local host directory "mods" in same directory as this compose file
      # all mods in this directory get copied into /data/mods at startup
      - ./mods:/mods:ro
      
volumes:
  # declared the named volume, but use default/local storage engine
  mc_forge: {}
